### ISSUE TITLE
webpack does not compile the client JavaScript properly

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2461]
Upon loading the page, the JavaScript encounters a runtime error:

```
Uncaught TypeError: data_1.colorsJSON is not iterable
    at colorsInit (colorsInit.ts:17:27)
    at Object../src/game/data/gameData.ts (gameData.ts:11:26)
    at __webpack_require__ (bootstrap:19:1)
    at Object../src/chatCommands.ts (chatCommands.ts:2:1)
    at __webpack_require__ (bootstrap:19:1)
    at Object../src/chat.ts (chat.ts:7:1)
    at __webpack_require__ (bootstrap:19:1)
    at Object../src/main.ts (main.ts:4:1)
    at __webpack_require__ (bootstrap:19:1)
    at startup:4:1
```

This is because the `colorsJSON` variable is undefined, when it is normally supposed to be an array.
For reference, the line of code that imports it is as follows:

```ts
import { colorsJSON } from "@hanabi/data";
```

This in turn imports it from the "data" monorepo package:

```ts
import * as colorsJSON from "./colors.json";
export { colorsJSON };
```

I see that the "colors.json" file does appear in the transpiled output:

```
/***/ "../../node_modules/@hanabi/data/dist/colors.json":
/*!********************************************************!*\
  !*** ../../node_modules/@hanabi/data/dist/colors.json ***!
  \********************************************************/
/***/ ((module) => {

"use strict";
module.exports = JSON.parse('[{"name":"Red","fill":"#e60000"},{"name":"Yellow","fill":"#e6e600"},{"name":"Green","fill":"#02ec00","fillColorblind":"#00aa00"},{"name":"Blue","fill":"#0037ff","fillColorblind":"#0055ff"},{"name":"Purple","fill":"#6600cc","fillColorblind":"#8800aa"},{"name":"Teal","fill":"#00cccc"},{"name":"Black","abbreviation":"K","fill":"#111111"},{"name":"Pink","abbreviation":"I","fill":"#ff69b4"},{"name":"Brown","abbreviation":"N","fill":"#654321"}]');

/***/ }),
```

However, it looks like it is under node_modules, so maybe that is a problem?

**Comment by DrAnax** [comment]
> However, it looks like it is under node_modules, so maybe that is a problem?

Shouldn't this happen in monorepo?

**Comment by Zamiell** [comment]
i have no idea

**Comment by DrAnax** [comment]
Now you do.

/close
