### ISSUE TITLE
Listing of variants with a filter resulting in no game played causes an error

### ISSUE THREAD

**Issue by N1trate** [Hanabi-Live/hanabi-live#2488]
If we go to a certain variant, i.e. : https://hanab.live/variant/1822
We can filter the number of players, in this case, 2, 3 and 4 are going to work.
If we filter with 5 or 6 it's going to break.

The following error is seen in the console.

```
1822:220 Uncaught TypeError: Cannot read properties of null (reading 'length')
    at Object.ajaxProcessing (1822:220:25)
    at R (jquery.tablesorter.pager-2.31.3.min.js:7:4907)
    at Object.F.t.ajax.t.processAjaxOnInit.T.isEmptyObject.r.ajaxObject.success (jquery.tablesorter.pager-2.31.3.min.js:7:12619)
    at c (jquery-3.5.0.min.js:2:28294)
    at Object.fireWith [as resolveWith] (jquery-3.5.0.min.js:2:29039)
    at l (jquery-3.5.0.min.js:2:79817)
    at XMLHttpRequest.<anonymous> (jquery-3.5.0.min.js:2:82271)
```

The page then "waits" and never get out of a loading icon, so we can't click on anything else until we reload the page.

**Comment by DrAnax** [comment]
Right, https://hanab.live/api/v1/variants/1822?fcol[1]=5 returns null and this isn't handled by the tablesorter.
