### ISSUE TITLE
Hydra spectating throw it in a hole isn't very exciting

### ISSUE THREAD

**Issue by DrAnax** [Hanabi-Live/hanabi-live#2610]
![image](https://user-images.githubusercontent.com/2622043/153774579-d786473c-d643-4e4a-ad47-1655a63a5f83.png)

```javascript
Uncaught Error: The suit index for the played card was: -1
    at gameStateReducer.ts:177:17
    at immerClass.ts:78:58
    at e.produce (immerClass.ts:94:14)
    at immerClass.ts:78:17
    at stateReducer.ts:302:23
    at Array.reduce (<anonymous>)
    at Wp (stateReducer.ts:301:24)
    at stateReducer.ts:25:32
    at immerClass.ts:78:58
    at e.produce (immerClass.ts:94:14)
```

**Comment by Zamiell** [comment]
lul
