### ISSUE TITLE
"Failed to get the previously known card identity for card: 50"

### ISSUE THREAD

**Issue by wjomlex** [Hanabi-Live/hanabi-live#2876]
**Describe the bug**
See screenshot. This error popped up right as the game (#1019942) ended. I saw it in a game last week as well (I believe #1016263) but failed to get the screenshot.

**To Reproduce**
Not sure except "finish a 3-player No Variant game". It was the first game I played today, and I want to say that when it happened last week it was also my first game? All subsequent games were fine. I played 3-player No Variant on Friday and those games were all fine.

**Screenshots**
![image](https://github.com/Hanabi-Live/hanabi-live/assets/6496674/7052e0e4-dddf-46a6-87cd-759728cedc63)

**Comment by HagenRo** [comment]
![image](https://github.com/Hanabi-Live/hanabi-live/assets/100077753/caada43b-302b-4fed-a068-0fc643d6fde8)
same situation here but with another variant.
This error popped up right as the game (#1022753) ended

**Comment by WillFlame14** [comment]
I also got this error at the end of game #1023178.
```
TypeError: Failed to get the previously known card identity for card: 50
    at Ce (https://hanab.live/public/js/bundles/main.6054.min.js:1:46728)
    at Ir.getCardIdentity (https://hanab.live/public/js/bundles/main.6054.min.js:11:25036)
    at Ir.setBareImage (https://hanab.live/public/js/bundles/main.6054.min.js:11:24445)
    at lg (https://hanab.live/public/js/bundles/main.6054.min.js:179:17000)
    at Object.LO [as onChange] (https://hanab.live/public/js/bundles/main.6054.min.js:179:19250)
    at i (https://hanab.live/public/js/bundles/main.6054.min.js:179:14069)
    at Object.C [as dispatch] (https://hanab.live/public/js/bundles/main.6054.min.js:168:28963)
    at https://hanab.live/public/js/bundles/main.6054.min.js:194:9422
    at Object.finishOngoingGame (https://hanab.live/public/js/bundles/main.6054.min.js:194:19880)
    at Jw.onMessage (https://hanab.live/public/js/bundles/main.6054.min.js:168:27295)
```

**Comment by Zamiell** [comment]
its a spectator bug that is fixed now
