### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by JelleZijlstra** [Hanabi-Live/hanabi-live#2879]
I got this error at the end of a game of cocoa rainbow + rainbow ones. It was after I misplayed a card at the very end of the game, but I don't have precise repro conditions.

```
TypeError: Failed to get the previously known card identity for card: 55
    at Ce (https://hanab.live/public/js/bundles/main.6054.min.js:1:46728)
    at Ir.getCardIdentity (https://hanab.live/public/js/bundles/main.6054.min.js:11:25036)
    at Ir.setBareImage (https://hanab.live/public/js/bundles/main.6054.min.js:11:24445)
    at lg (https://hanab.live/public/js/bundles/main.6054.min.js:179:17000)
    at Object.LO [as onChange] (https://hanab.live/public/js/bundles/main.6054.min.js:179:19250)
    at i (https://hanab.live/public/js/bundles/main.6054.min.js:179:14069)
    at Object.C [as dispatch] (https://hanab.live/public/js/bundles/main.6054.min.js:168:28963)
    at https://hanab.live/public/js/bundles/main.6054.min.js:194:9422
    at Object.finishOngoingGame (https://hanab.live/public/js/bundles/main.6054.min.js:194:19880)
    at Jw.onMessage (https://hanab.live/public/js/bundles/main.6054.min.js:168:27295)
```

A popup appeared telling me to report a bug here.

**Comment by Romain672** [comment]
It happened to me twice in a row (with a rematch in between), and never in another moment.

Firefox user.

**Comment by Zamiell** [comment]
this is a spectator bug that is now fixed
