### ISSUE TITLE
Hanabi Crashed During Replay with a Bottom Deck Blind Play in Hypothetical

### ISSUE THREAD

**Issue by Jacob-Lisner** [Hanabi-Live/hanabi-live#2892]
**Describe the bug**
During the review of a replay with bottom deck blind plays, during a hypothetical a bottom deck blind play was attempted and the entire replay crashed. Reloading does not fix the error. Here is the error report:

TypeError: Failed to find the card at order: 54
    at Se (https://hanab.live/public/js/bundles/main.6082.min.js:1:46727)
    at Xq (https://hanab.live/public/js/bundles/main.6082.min.js:172:50111)
    at https://hanab.live/public/js/bundles/main.6082.min.js:13:109459
    at tV.produce (https://hanab.live/public/js/bundles/main.6082.min.js:13:109604)
    at https://hanab.live/public/js/bundles/main.6082.min.js:13:109444
    at pL (https://hanab.live/public/js/bundles/main.6082.min.js:172:55857)
    at $q (https://hanab.live/public/js/bundles/main.6082.min.js:172:54280)
    at https://hanab.live/public/js/bundles/main.6082.min.js:13:109459
    at tV.produce (https://hanab.live/public/js/bundles/main.6082.min.js:13:109604)
    at https://hanab.live/public/js/bundles/main.6082.min.js:13:109444

**To Reproduce**
Not certain since it crashes on reload, but this is the replay:
https://hanab.live/shared-replay/1069321#62

**Comment by shemetz** [comment]
This keeps happening to me too, can confirm!

As a workaround when it happens to you - use devtools to delete the blocking elements and then close the game

**Comment by Ten0** [comment]
When doing in an end of game review we all got stuck in the end of game review, where reloading would get us on the error page and we couldn't click lobby 😱

**Comment by Zamiell** [comment]
should be fixed now
