### ISSUE TITLE
website told me to report this

### ISSUE THREAD

**Issue by TheDaniMan** [Hanabi-Live/hanabi-live#2926]
I was just spectating a game, I might have gone into history a few times

TypeError: Failed to get card of order 24 from the deck.
    at ve (https://hanab.live/public/js/bundles/main.6313.min.js:5:285677)
    at ri (https://hanab.live/public/js/bundles/main.6313.min.js:32:57502)
    at https://hanab.live/public/js/bundles/main.6313.min.js:200:10115
    at https://hanab.live/public/js/bundles/main.6313.min.js:200:19869
    at cb.onMessage (https://hanab.live/public/js/bundles/main.6313.min.js:174:114058)

**Comment by TheDaniMan** [comment]
and another one in another game not much later, during a review:
Error: The UI collection is out of sync with the state.
    at Yb (https://hanab.live/public/js/bundles/main.6313.min.js:185:19985)
    at Object.mE [as onChange] (https://hanab.live/public/js/bundles/main.6313.min.js:185:17948)
    at i (https://hanab.live/public/js/bundles/main.6313.min.js:185:14069)
    at https://hanab.live/public/js/bundles/main.6313.min.js:174:115621
    at Map.forEach ()
    at Object.v [as dispatch] (https://hanab.live/public/js/bundles/main.6313.min.js:174:115608)
    at https://hanab.live/public/js/bundles/main.6313.min.js:200:9679
    at https://hanab.live/public/js/bundles/main.6313.min.js:200:19869
    at cb.onMessage (https://hanab.live/public/js/bundles/main.6313.min.js:174:114058)

**Comment by DarthGandalf** [comment]
TypeError: Failed to get card of order 35 from the deck.
    at _e (https://hanab.live/public/js/bundles/main.6328.min.js:5:285677)
    at ri (https://hanab.live/public/js/bundles/main.6328.min.js:32:57499)
    at https://hanab.live/public/js/bundles/main.6328.min.js:200:10115
    at https://hanab.live/public/js/bundles/main.6328.min.js:200:19870
    at pb.onMessage (https://hanab.live/public/js/bundles/main.6328.min.js:174:114058)

**Comment by Zamiell** [comment]
the first error is fixed now, provide steps to reproduce the second one
