### ISSUE TITLE
The UI collection is out of sync with the state.

### ISSUE THREAD

**Issue by Kowalski1337** [Hanabi-Live/hanabi-live#2945]
**Describe the bug**
Error pop-up appeared while I was reviewing game
https://hanab.live/shared-replay/1173240
It happened 3 times

**To Reproduce**

1. Enter the shared replay
2. Do nothing

**Expected behavior**
Not seeing this pop-up

**Screenshots**

**Additional context**
Error message:
```
Error: The UI collection is out of sync with the state.
    at xb (https://hanab.live/public/js/bundles/main.6356.min.js:185:19985)
    at Object._E [as onChange] (https://hanab.live/public/js/bundles/main.6356.min.js:185:17838)
    at i (https://hanab.live/public/js/bundles/main.6356.min.js:185:14069)
    at https://hanab.live/public/js/bundles/main.6356.min.js:174:115621
    at Map.forEach ()
    at Object.v [as dispatch] (https://hanab.live/public/js/bundles/main.6356.min.js:174:115608)
    at https://hanab.live/public/js/bundles/main.6356.min.js:200:9554
    at https://hanab.live/public/js/bundles/main.6356.min.js:200:19870
    at gb.onMessage (https://hanab.live/public/js/bundles/main.6356.min.js:174:114058)
```

**Comment by username-AThing69** [comment]
i have the exact same problem

**Comment by WillFlame14** [comment]
This consistently reproduced the bug:
1. Create a shared replay for game 1100892 and have at least 1 other player join.
2. Enter hypo on turn 10 and show hidden cards.
3. hallmark clues red to WillFlame on turn 9 (should touch o5, r2 and r4).
4. WillFlame plays g1 (slot 1) on turn 10.
5. Undo the most recent turn.
6. Redo the most recent turn.
7. Refresh the page.

To escape, have the other player /setleader and exit hypo.

**Comment by WillFlame14** [comment]
It looks like upon exiting hypo, the game ends up at around turn 15 even though it should be on turn 9. That might be related to how it's out of sync?
