### ISSUE TITLE
Crash when viewing replay

### ISSUE THREAD

**Issue by the-rivulet** [Hanabi-Live/hanabi-live#2947]
**Describe the bug**
Website displays error when opening replay that I was a member of.
```
TypeError: Cannot read properties of undefined (reading 'location')
    at b4 (https://hanab.live/public/js/bundles/main.6356.min.js:5:717605)
    at nK (https://hanab.live/public/js/bundles/main.6356.min.js:5:741585)
    at https://hanab.live/public/js/bundles/main.6356.min.js:5:736626
    at UJ.produce (https://hanab.live/public/js/bundles/main.6356.min.js:5:736771)
    at https://hanab.live/public/js/bundles/main.6356.min.js:5:736611
    at rK (https://hanab.live/public/js/bundles/main.6356.min.js:5:748279)
    at https://hanab.live/public/js/bundles/main.6356.min.js:5:736626
    at UJ.produce (https://hanab.live/public/js/bundles/main.6356.min.js:5:736771)
    at https://hanab.live/public/js/bundles/main.6356.min.js:5:736611
    at f6 (https://hanab.live/public/js/bundles/main.6356.min.js:174:120673)
```

**To Reproduce**

1. Go to hanab.live
2. Automatically join replay
3. See error

**Expected behavior**
Expected the replay to load normally

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Zamiell** [comment]
what replay was it? how to reproduce the error using a brand new account?

**Comment by Zamiell** [comment]
should be fixed in https://github.com/Hanabi-Live/hanabi-live/commit/a8ec90dc9b74b7d8f1b74843054dfe8da7cca38b
