### ISSUE TITLE
Error: The UI collection is out of sync with the state.

### ISSUE THREAD

**Issue by Kowalski1337** [Hanabi-Live/hanabi-live#2954]
**Describe the bug**

**To Reproduce**

https://hanab.live/shared-replay/1219634#25

**Expected behavior**

**Screenshots**

**Additional context**
Error: The UI collection is out of sync with the state.
    at Lb (https://hanab.live/public/js/bundles/main.6387.min.js:185:20561)
    at Object.DE [as onChange] (https://hanab.live/public/js/bundles/main.6387.min.js:185:18414)
    at i (https://hanab.live/public/js/bundles/main.6387.min.js:185:14645)
    at https://hanab.live/public/js/bundles/main.6387.min.js:174:115625
    at Map.forEach ()
    at Object.v [as dispatch] (https://hanab.live/public/js/bundles/main.6387.min.js:174:115612)
    at https://hanab.live/public/js/bundles/main.6387.min.js:200:9668
    at https://hanab.live/public/js/bundles/main.6387.min.js:200:20209
    at wb.onMessage (https://hanab.live/public/js/bundles/main.6387.min.js:174:114062)

**Comment by Zamiell** [comment]
I clicked on the link and I don't get any error. Provide actual steps to reproduce the problem
